### 레스토랑 생성
GRAPHQL {{host}}/graphql
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjkxMzk1OTQzfQ.WF1fhAH3j3vrkRYRAct4AwYmQe1-2TiEWY8-HY5VZSg

mutation {
  createRestaurant(input:{
    name: "식당22222"
    coverImg: "https://"
    address: "주소22222"
    categoryName: "카테고리1"
  }){
    ok
    error
  }
}

> {%
  client.test("response check", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });

  client.test("return value check", function() {
    client.assert(response.body.data.createRestaurant.ok === true, "ok is not true");
  });
%}