### Dish(레스토랑에서 파는 메뉴) 생성
GRAPHQL {{host}}/graphql
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjkyMTY1NTYxfQ.rXMao0wVpp0E7COCIvJiNp6F2wV2lczL5Lzy7Lqligs

mutation {
  createDish(input:{
    name:"메뉴 - 쫄면"
    price:8
    description:"두번째 메뉴"
    restaurantId:1
    options:[
      {name:"계란추가", extra:1},
      {name:"맵기", choices:[{name:"보통", extra:1}, {name:"더 맵게", extra:2}]},
      {name:"양", choices:[{name:"많이", extra:1}, {name:"더 많이", extra:2}]}
    ]
  }){
    ok
    error
  }
}

> {%
    client.test("response check", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("return value check", function () {
        client.assert(response.body.data.createDish.ok === true, "ok is not true");
    });
%}

### Dish 수정
GRAPHQL {{host}}/graphql
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNjkxMzk2NTYxfQ.FFLyq5ACU1K7xCSb7isbk-toMcYH0r9pkg7ZJtdYRIg

mutation {
  editDish(input:{
    name:"333333->수정"
    price: 22
    description: "333333->수정"
    dishId:6
    options:[
      {name:"opt1-1", extra:3},
      {name:"opt2-1", choices:[{name:"subopt1-1", extra:1}, {name:"subopt2-1", extra:2}]}
    ]
  }){
    ok
    error
  }
}

> {%
    client.test("response check", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("return value check", function () {
        client.assert(response.body.data.editDish.ok === true, "ok is not true");
    });
%}

### Dish 삭제
GRAPHQL {{host}}/graphql
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNjkxMzk2NTA5fQ.KX_rwaJD9EL4hmBXSK1v4x6UJEBHZVV-7LZ3SDnM9f4

mutation {
  deleteDish(input:{
    dishId: 1
  }){
    ok
    error
  }
}

> {%
    client.test("response check", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("return value check", function () {
        client.assert(response.body.data.deleteDish.ok === true, "ok is not true");
    });
%}