### Dish(레스토랑에서 파는 메뉴) 생성
GRAPHQL {{host}}/graphql
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzA1MDM2NDI4fQ.8VLOARgAJb4mLMp2KMBmkRjTSzgWxGlWOPRmqaiuWdk

mutation {
  createDish(input:{
    name:"스파아시 버거"
    price:10
    description:"아주 매운맛!!"
    restaurantId:1
    options:[
      {name:"덜 맵게", extra:0},
      {name:"감자튀김 추가", extra:2},
    ]
  }){
    ok
    error
  }
}

> {%
    client.test("response check", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("return value check", function () {
        client.assert(response.body['data']['createDish']['ok'] === true, "ok is not true");
    });
%}

### Dish 수정
GRAPHQL {{host}}/graphql
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNjkxMzk2NTYxfQ.FFLyq5ACU1K7xCSb7isbk-toMcYH0r9pkg7ZJtdYRIg

mutation {
  editDish(input:{
    name:"333333->수정"
    price: 22
    description: "333333->수정"
    dishId:6
    options:[
      {name:"opt1-1", extra:3},
      {name:"opt2-1", choices:[{name:"subopt1-1", extra:1}, {name:"subopt2-1", extra:2}]}
    ]
  }){
    ok
    error
  }
}

> {%
    client.test("response check", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("return value check", function () {
        client.assert(response.body.data.editDish.ok === true, "ok is not true");
    });
%}

### Dish 삭제
GRAPHQL {{host}}/graphql
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNjkxMzk2NTA5fQ.KX_rwaJD9EL4hmBXSK1v4x6UJEBHZVV-7LZ3SDnM9f4

mutation {
  deleteDish(input:{
    dishId: 1
  }){
    ok
    error
  }
}

> {%
    client.test("response check", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("return value check", function () {
        client.assert(response.body.data.deleteDish.ok === true, "ok is not true");
    });
%}
