### 파일 업로드
POST {{host}}/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.png"
Content-Type: image/png

< ./test.png
--WebAppBoundary--
