### 주문
GRAPHQL {{host}}/graphql
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjkyMTY2MDM2fQ.1HjJzYCp8KEqusnlXbv0-3F8hL1MyZPayG5skH-omm0

mutation {
  createOrder(input:{
    restaurantId: 1
    items:[
      {
        dishId: 1,
        options: [{name: "더 많이"}, {name: "맵기", choice:"보통"}]
      },
      {
        dishId: 2,
        options: [{name: "계란추가"}, {name: "맵기", choice:"보통"}, {name: "양", choice:"많이"}]
      }
    ]
  }){
    ok
    error
  }
}

> {%
  client.test("response check", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });

  client.test("return value check", function() {
    client.assert(response.body.data.createOrder.ok === true, "ok is not true");
  });
%}

### 주문 단건 조회
GRAPHQL {{host}}/graphql
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjkyNjU2OTI3fQ.4aDdZYso1QHsfeOtafLaHuqNWpFsNF38mJz7Y-cgUo0

query {
  viewOrder(input:{
    orderId: 6
  }){
    ok
    error
    orderInfo {
      restaurant {
        name
        address
      }
      items {
        options {
          name
          choice
        }
      }
      total
      status
    }
  }
}

> {%
  client.test("response check", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });

  client.test("return value check", function() {
    client.assert(response.body.data.viewOrder.ok === true, "ok is not true");
  });
%}

### 주문 리스트 조회
GRAPHQL {{host}}/graphql
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjkzMDE3MjUyfQ.1DBcHOkaFz680FZ6p_WHbA1SJUYUcz0-qkm-KaGYWLg

query {
  viewOrders(input:{
    status: Cooked
  }){
    ok
    error
    orders {
      status
      total
    }
  }
}

> {%
  client.test("response check", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });

  client.test("return value check", function() {
    client.assert(response.body.data.viewOrders.ok === true, "ok is not true");
  });
%}

### 주문 수정
GRAPHQL {{host}}/graphql
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjkzNzg1ODMyfQ.GRCsvuwlBMMRV6bXOB6zBIrqIbn2lHsqjsdFdgNs_x0

mutation {
  editOrder(input:{
    id: 6
    status: Delivered
  }){
    ok
    error
  }
}

> {%
  client.test("response check", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });

  client.test("return value check", function() {
    client.assert(response.body.data.editOrder.ok === true, "ok is not true");
  });
%}

### 배달원 주문 수락
GRAPHQL {{host}}/graphql
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNjkzNzg1Mzk0fQ.o57pgDAqAw6bZY0EWIQx4Eo8--beJUTXC0ulgRt-NuY

mutation {
  takeOrder(input:{
    id: 6
  }){
    ok
    error
  }
}

> {%
  client.test("response check", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });

  client.test("return value check", function() {
    client.assert(response.body.data.takeOrder.ok === true, "ok is not true");
  });
%}