### subscription 실행
GRAPHQL {{host}}/graphql
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjkzMDE3MjUyfQ.1DBcHOkaFz680FZ6p_WHbA1SJUYUcz0-qkm-KaGYWLg

subscription {
  pendingOrders{
    id
    items {
      dish {
        name
      }
      options {
        name
        choice
      }
    }
  }
}

> {%
  client.test("response check", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });

  client.test("return value check", function() {
    client.assert(response.body.data.createAccount.ok === true, "ok is not true");
  });
%}

### subscription 외부 호출
GRAPHQL {{host}}/graphql
x-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjkzMDE3MjUyfQ.1DBcHOkaFz680FZ6p_WHbA1SJUYUcz0-qkm-KaGYWLg

mutation {
  fireEvent(id: 3)
}

> {%
  client.test("response check", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}



